export const doctors = [
  {
    id: 1,
    name: "Dr. Ahmed Hassan",
    specialty: "Cardiologist",
    image: "/images/doctors/img1.png",
    details: "Expert in heart diseases and cardiovascular health.",
    link: "/jobs/ahmed-hassan",
    avatar: "/images/avatar.jpg",
    remotely: true,
    price: 200,
    fromDate: "2025-07-10",
    toDate: "2025-07-15",
    location: "Egypt, Cairo",
    title: "Dr. Ahmed Hassan",
    description: "Expert in heart diseases and cardiovascular health.",
    type: "Remote",
    posted: "2025-07-10 - 2025-07-15",
  },
  {
    id: 2,
    name: "Dr. Sara Ali",
    specialty: "Dermatologist",
    image: "/images/doctors/img2.png",
    details: "Specialist in skin care and dermatological treatments.",
    link: "/jobs/sara-ali",
    avatar: "/images/avatar.jpg",
    remotely: false,
    price: 180,
    fromDate: "2025-07-12",
    toDate: "2025-07-18",
    location: "KSA, Riyadh",
    title: "Dr. Sara Ali",
    description: "Specialist in skin care and dermatological treatments.",
    type: "Onsite",
    posted: "2025-07-12 - 2025-07-18",
  },
  {
    id: 3,
    name: "Dr. Omar Youssef",
    specialty: "Pediatrician",
    image: "/images/doctors/img3.png",
    details: "Caring for children and infants with compassion.",
    link: "/jobs/omar-youssef",
    avatar: "/images/avatar.jpg",
    remotely: true,
    price: 150,
    fromDate: "2025-07-14",
    toDate: "2025-07-20",
    location: "UAE, Dubai",
    title: "Dr. Omar Youssef",
    description: "Caring for children and infants with compassion.",
    type: "Remote",
    posted: "2025-07-14 - 2025-07-20",
  },
  {
    id: 4,
    name: "Dr. Ahmed Hassan",
    specialty: "Cardiologist",
    image: "/images/doctors/img1.png",
    details: "Expert in heart diseases and cardiovascular health.",
    link: "/jobs/ahmed-hassan",
    avatar: "/images/avatar.jpg",
    remotely: true,
    price: 200,
    fromDate: "2025-07-10",
    toDate: "2025-07-15",
    location: "USA, New York",
    title: "Dr. Ahmed Hassan",
    description: "Expert in heart diseases and cardiovascular health.",
    type: "Remote",
    posted: "2025-07-10 - 2025-07-15",
  },
  {
    id: 5,
    name: "Dr. Sara Ali",
    specialty: "Dermatologist",
    image: "/images/doctors/img2.png",
    details: "Specialist in skin care and dermatological treatments.",
    link: "/jobs/sara-ali",
    avatar: "/images/avatar.jpg",
    remotely: false,
    price: 180,
    fromDate: "2025-07-12",
    toDate: "2025-07-18",
    location: "Egypt, Cairo",
    title: "Dr. Sara Ali",
    description: "Specialist in skin care and dermatological treatments.",
    type: "Onsite",
    posted: "2025-07-12 - 2025-07-18",
  },
  {
    id: 6,
    name: "Dr. Omar Youssef",
    specialty: "Pediatrician",
    image: "/images/doctors/img3.png",
    details: "Caring for children and infants with compassion.",
    link: "/jobs/omar-youssef",
    avatar: "/images/avatar.jpg",
    remotely: true,
    price: 150,
    fromDate: "2025-07-14",
    toDate: "2025-07-20",
    location: "KSA, Riyadh",
    title: "Dr. Omar Youssef",
    description: "Caring for children and infants with compassion.",
    type: "Remote",
    posted: "2025-07-14 - 2025-07-20",
  },
]; 